api_platform:
    title: Hello API Platform
    version: 1.0.0
    formats:
        jsonld: ['application/ld+json']
        jsonhal:  ['application/hal+json']
        jsonapi:  ['application/vnd.api+json']
        json:     ['application/json']
        xml:      ['application/xml', 'text/xml']
        yaml:     ['application/x-yaml']
        csv:      ['text/csv']
        html:     ['text/html']
        myformat: ['application/vnd.myformat'] 
    docs_formats:
        jsonld: ['application/ld+json']
        jsonopenapi: ['application/vnd.openapi+json']
        html: ['text/html']
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
            rfc_7807_compliant_errors: true
        pagination_enabled: false
    event_listeners_backward_compatibility_layer: false
    keep_legacy_inflector: false

    collection:
            # The name of the query parameter to filter nullable results (with the ExistsFilter).
            exists_parameter_name: 'exists'

            # The default order of results.
            order: 'ASC'

            # The name of the query parameter to order results (with the OrderFilter).
            order_parameter_name: 'order'

            pagination:

                enabled: false
                # The default name of the parameter handling the page number.
                page_parameter_name: 'page'

                # The name of the query parameter to enable or disable pagination.
                enabled_parameter_name: 'pagination'

                # The name of the query parameter to set the number of items per page.
                items_per_page_parameter_name: 'itemsPerPage'

                # The name of the query parameter to enable or disable the partial pagination.
                partial_parameter_name: 'partial'

                # items_per_page: 5

                # client_enable : true